# Copied from kotlinc
org.gradle.jvmargs=-Duser.country=US -Dkotlin.daemon.jvm.options=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.parallel=true

kotlinBaseVersion=2.3.20
kotlinxSerializationVersion=1.6.3
agpBaseVersion=9.3.0-alpha01
aaKotlinBaseVersion=2.4.20-dev-6138
aaIntellijVersion=251.27812.49
aaFastutilVersion=8.5.14-jb1
aaCoroutinesVersion=1.10.2

kotlin.jvm.target.validation.mode=warning

# Build or runtime dependencies of this project
buildKotlinVersion=2.3.20
buildKspVersion=2.3.5
