/*
 * Copyright 2026 Google LLC
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSVisitorVoid
import com.google.devtools.ksp.validate
import java.io.OutputStream

/**
 * A code generator, called a processor, that uses KSP.
 * It implements the [SymbolProcessor] interface that comes from KSP.
 */
class HelloWorldProcessor(val codeGenerator: CodeGenerator) : SymbolProcessor {

    /**
     * Selects functions annotated with `Gen` generates `helloWorld`.
     * Always returns an empty list since it either generates the `helloWorld` function or not.
     */
    override fun process(resolver: Resolver): List<KSAnnotated> {
        resolver
            .getSymbolsWithAnnotation("com.example.annotations.Gen")
            .filter { it.validate() }
            .filterIsInstance<KSFunctionDeclaration>()
            .forEach { it.accept(HelloWorldVisitor(), Unit) }

        return emptyList()
    }

    /**
     * Local visitor for the KSP AST.
     * It extends the [KSVisitorVoid] which knows how to traverse the AST, but
     * only overrides the `visitFunctionDeclaration` method, since it is only ever passed
     * the handle to the `main` function.
     */
    inner class HelloWorldVisitor : KSVisitorVoid() {

        /**
         * Generates the `helloWorld` function.
         */
        override fun visitFunctionDeclaration(function: KSFunctionDeclaration, data: Unit) {
            createNewFileFrom(function).use { file ->
                file.write(
                    """
                        fun helloWorld(): Unit {
                            println("Hello world from function generated by KSP")
                        }
                    """.trimIndent()
                )
            }
        }
    }

    /**
     * Creates a new file for `function`.
     */
    private fun createNewFileFrom(function: KSFunctionDeclaration): OutputStream {
        return codeGenerator.createNewFile(
            dependencies = createDependencyOn(function),
            packageName = "",
            fileName = "GeneratedHelloWorld"
        )
    }

    /**
     * Creates a dependency for the file containing `function`.
     */
    private fun createDependencyOn(function: KSFunctionDeclaration): Dependencies {
        return Dependencies(aggregating = false, function.containingFile!!)
    }

}
