package com.google.devtools.ksp.standalone

import com.intellij.openapi.Disposable
import com.intellij.openapi.project.Project
import com.intellij.openapi.util.Disposer
import com.intellij.openapi.vfs.VirtualFile
import com.intellij.psi.search.GlobalSearchScope
import org.jetbrains.kotlin.analysis.api.KaPlatformInterface
import org.jetbrains.kotlin.analysis.api.platform.packages.KotlinCompositePackageProvider
import org.jetbrains.kotlin.analysis.api.platform.packages.KotlinPackageProvider
import org.jetbrains.kotlin.analysis.api.platform.packages.KotlinPackageProviderFactory
import org.jetbrains.kotlin.analysis.api.standalone.base.packages.KotlinStandalonePackageProviderFactory
import org.jetbrains.kotlin.psi.KtFile

@OptIn(KaPlatformInterface::class)
class IncrementalKotlinPackageProviderFactory(
    private val project: Project,
    libraryRoots: List<VirtualFile> = emptyList(),
) : KotlinPackageProviderFactory, Disposable {
    private val staticFactories: MutableList<KotlinStandalonePackageProviderFactory> = mutableListOf()

    init {
        // Binary library roots (KLIBs/JARs) are static and known at session creation time.
        // We create a dedicated factory for them once so they are indexed upfront.
        if (libraryRoots.isNotEmpty()) {
            val libFactory = KotlinStandalonePackageProviderFactory(
                project = project,
                indexedFiles = emptyList(),
                libraryRoots = libraryRoots,
            )
            Disposer.register(this, libFactory)
            staticFactories.add(libFactory)
        }
    }

    override fun createPackageProvider(searchScope: GlobalSearchScope): KotlinPackageProvider {
        val providers = staticFactories.map { it.createPackageProvider(searchScope) }
        return KotlinCompositePackageProvider.create(providers)
    }

    fun update(files: Collection<KtFile>) {
        // Skip adding an empty factory if this round generated no new Kotlin files.
        if (files.isEmpty()) return

        // New source files generated by processors are incrementally added per round.
        // libraryRoots is intentionally empty here: binary libraries are invariant across rounds,
        // so passing libraryRoots again would redundantly duplicate KLIB parsing and Caffeine caching.
        val staticFactory = KotlinStandalonePackageProviderFactory(
            project = project,
            indexedFiles = files,
            libraryRoots = emptyList(),
        )
        Disposer.register(this, staticFactory)
        staticFactories.add(staticFactory)
    }

    override fun dispose() {
    }
}
