/*
 * Copyright 2010-2020 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.ksp.test;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("plugins/ksp/testData/api")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class KotlinKSPTestGenerated extends AbstractKotlinKSPTest {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, this, testDataFilePath);
    }

    public void testAllFilesPresentInApi() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("plugins/ksp/testData/api"), Pattern.compile("^(.+)\\.kt$"), null, false);
    }

    @TestMetadata("allFunctions.kt")
    public void testAllFunctions() throws Exception {
        runTest("plugins/ksp/testData/api/allFunctions.kt");
    }

    @TestMetadata("annotationValue.kt")
    public void testAnnotationValue() throws Exception {
        runTest("plugins/ksp/testData/api/annotationValue.kt");
    }

    @TestMetadata("annotationWithDefault.kt")
    public void testAnnotationWithDefault() throws Exception {
        runTest("plugins/ksp/testData/api/annotationWithDefault.kt");
    }

    @TestMetadata("builtInTypes.kt")
    public void testBuiltInTypes() throws Exception {
        runTest("plugins/ksp/testData/api/builtInTypes.kt");
    }

    @TestMetadata("checkOverride.kt")
    public void testCheckOverride() throws Exception {
        runTest("plugins/ksp/testData/api/checkOverride.kt");
    }

    @TestMetadata("classKinds.kt")
    public void testClassKinds() throws Exception {
        runTest("plugins/ksp/testData/api/classKinds.kt");
    }

    @TestMetadata("companion.kt")
    public void testCompanion() throws Exception {
        runTest("plugins/ksp/testData/api/companion.kt");
    }

    @TestMetadata("declarationPackageName.kt")
    public void testDeclarationPackageName() throws Exception {
        runTest("plugins/ksp/testData/api/declarationPackageName.kt");
    }

    @TestMetadata("errorTypes.kt")
    public void testErrorTypes() throws Exception {
        runTest("plugins/ksp/testData/api/errorTypes.kt");
    }

    @TestMetadata("functionTypeAlias.kt")
    public void testFunctionTypeAlias() throws Exception {
        runTest("plugins/ksp/testData/api/functionTypeAlias.kt");
    }

    @TestMetadata("hello.kt")
    public void testHello() throws Exception {
        runTest("plugins/ksp/testData/api/hello.kt");
    }

    @TestMetadata("implicitElements.kt")
    public void testImplicitElements() throws Exception {
        runTest("plugins/ksp/testData/api/implicitElements.kt");
    }

    @TestMetadata("interfaceWithDefault.kt")
    public void testInterfaceWithDefault() throws Exception {
        runTest("plugins/ksp/testData/api/interfaceWithDefault.kt");
    }

    @TestMetadata("javaModifiers.kt")
    public void testJavaModifiers() throws Exception {
        runTest("plugins/ksp/testData/api/javaModifiers.kt");
    }

    @TestMetadata("javaTypes.kt")
    public void testJavaTypes() throws Exception {
        runTest("plugins/ksp/testData/api/javaTypes.kt");
    }

    @TestMetadata("javaTypes2.kt")
    public void testJavaTypes2() throws Exception {
        runTest("plugins/ksp/testData/api/javaTypes2.kt");
    }

    @TestMetadata("makeNullable.kt")
    public void testMakeNullable() throws Exception {
        runTest("plugins/ksp/testData/api/makeNullable.kt");
    }

    @TestMetadata("platformDeclaration.kt")
    public void testPlatformDeclaration() throws Exception {
        runTest("plugins/ksp/testData/api/platformDeclaration.kt");
    }

    @TestMetadata("referenceElement.kt")
    public void testReferenceElement() throws Exception {
        runTest("plugins/ksp/testData/api/referenceElement.kt");
    }

    @TestMetadata("resolveJavaType.kt")
    public void testResolveJavaType() throws Exception {
        runTest("plugins/ksp/testData/api/resolveJavaType.kt");
    }

    @TestMetadata("typeAlias.kt")
    public void testTypeAlias() throws Exception {
        runTest("plugins/ksp/testData/api/typeAlias.kt");
    }

    @TestMetadata("typeAliasComparison.kt")
    public void testTypeAliasComparison() throws Exception {
        runTest("plugins/ksp/testData/api/typeAliasComparison.kt");
    }

    @TestMetadata("typeComposure.kt")
    public void testTypeComposure() throws Exception {
        runTest("plugins/ksp/testData/api/typeComposure.kt");
    }

    @TestMetadata("typeParameterReference.kt")
    public void testTypeParameterReference() throws Exception {
        runTest("plugins/ksp/testData/api/typeParameterReference.kt");
    }

    @TestMetadata("varianceTypeCheck.kt")
    public void testVarianceTypeCheck() throws Exception {
        runTest("plugins/ksp/testData/api/varianceTypeCheck.kt");
    }

    @TestMetadata("visibilities.kt")
    public void testVisibilities() throws Exception {
        runTest("plugins/ksp/testData/api/visibilities.kt");
    }
}
