/*
 * Copyright 2026 Google LLC
 * Copyright 2010-2026 JetBrains s.r.o. and Kotlin Programming Language contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.devtools.ksp.impl.symbol.kotlin.synthetic

import com.google.devtools.ksp.common.KSObjectCache
import com.google.devtools.ksp.impl.symbol.kotlin.AbstractKSDeclarationImpl
import com.google.devtools.ksp.impl.symbol.kotlin.KSExpectActualImpl
import com.google.devtools.ksp.impl.symbol.kotlin.KSPropertyDeclarationImpl
import com.google.devtools.ksp.impl.symbol.kotlin.Restorable
import com.google.devtools.ksp.impl.symbol.kotlin.defer
import com.google.devtools.ksp.symbol.KSBackingField
import com.google.devtools.ksp.symbol.KSExpectActual
import com.google.devtools.ksp.symbol.KSName
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.google.devtools.ksp.symbol.KSTypeReference
import com.google.devtools.ksp.symbol.KSVisitor
import org.jetbrains.kotlin.analysis.api.symbols.KaDeclarationSymbol
import org.jetbrains.kotlin.analysis.api.symbols.KaSyntheticJavaPropertySymbol

/**
 * Represents a backing field of a synthetic Java property.
 *
 * A synthetic Java property is generated by the Kotlin compiler when Kotlin code references a Java field.
 * The problem is that [KaSyntheticJavaPropertySymbol] is the synthetic property symbol, which states
 * that there is a backing field available (there is a 1:1 correspondence between properties and fields in Java).
 * However, the class does not provide access to the field itself or the declared Java property.
 */
class KSSyntheticJavaBackingFieldImpl private constructor(
    val kaSyntheticJavaPropertySymbol: KaSyntheticJavaPropertySymbol
) :
    KSBackingField,
    AbstractKSDeclarationImpl(),
    KSExpectActual by KSExpectActualImpl(kaSyntheticJavaPropertySymbol) {

    override val ktDeclarationSymbol: KaDeclarationSymbol get() = kaSyntheticJavaPropertySymbol

    companion object : KSObjectCache<KaSyntheticJavaPropertySymbol, KSSyntheticJavaBackingFieldImpl>() {
        fun getCached(symbol: KaSyntheticJavaPropertySymbol) =
            cache.getOrPut(symbol) { KSSyntheticJavaBackingFieldImpl(symbol) }
    }

    override val property: KSPropertyDeclaration by lazy {
        KSPropertyDeclarationImpl.getCached(kaSyntheticJavaPropertySymbol)
    }

    override val type: KSTypeReference by lazy {
        KSPropertyDeclarationImpl.getCached(kaSyntheticJavaPropertySymbol).type
    }

    override val qualifiedName: KSName? by lazy {
        KSPropertyDeclarationImpl.getCached(kaSyntheticJavaPropertySymbol).qualifiedName
    }

    override fun defer(): Restorable =
        kaSyntheticJavaPropertySymbol.defer(::getCached)

    override fun <D, R> accept(visitor: KSVisitor<D, R>, data: D): R =
        visitor.visitBackingField(this, data)
}
